//
//  ZettelWindowManager.swift
//  ZettelMac
//
//  Manages multiple Zettel note windows.
//  Each window is an NSPanel hosting a ZettelEditorView with its own state.
//

import AppKit
import SwiftUI
import ZettelKit

/// Manages all Zettel note windows — creation, focus, pinning, and lifecycle.
@MainActor
final class ZettelWindowManager: NSObject, ObservableObject {
    static let shared = ZettelWindowManager()

    // MARK: - State

    /// All active window states keyed by window ID
    private(set) var windowStates: [UUID: ZettelWindowState] = [:]

    /// NSWindow references keyed by window ID
    private var nsWindows: [UUID: NSWindow] = [:]

    /// Custom click-to-edit title views keyed by window ID
    private var titleViews: [UUID: TitlebarTitleView] = [:]

    /// Delegates kept alive keyed by window ID
    private var windowDelegates: [UUID: ZettelWindowDelegate] = [:]

    /// Last focused window (for keyboard shortcut routing)
    private(set) var lastFocusedWindowId: UUID?

    private override init() {
        super.init()
    }

    // MARK: - Window Creation

    /// Create a new Zettel window, optionally preloaded with a note.
    @discardableResult
    func createWindow(note: Note? = nil) -> UUID {
        let windowId = UUID()
        let state = ZettelWindowState(windowId: windowId, note: note)
        windowStates[windowId] = state

        let panel = createPanel(windowId: windowId, state: state)
        nsWindows[windowId] = panel

        showWindow(id: windowId)
        
        // Ensure notes are loaded
        Task {
            await MacNoteStore.shared.loadAllNotes()
        }

        return windowId
    }

    // MARK: - Actions (dispatched from menu commands)

    /// New note in the currently focused window (Cmd+N)
    func newNoteInCurrentWindow() {
        if let focusedId = lastFocusedWindowId, let state = windowStates[focusedId] {
            state.clearToNewNote()
            updateWindowTitle(id: focusedId)
        } else {
            createWindow()
        }
    }

    /// Toggle the note picker modal in the current window (Cmd+O)
    func togglePickerInCurrentWindow() {
        if let focusedId = lastFocusedWindowId, let state = windowStates[focusedId] {
            state.isShowingPicker.toggle()
        }
    }

    /// Toggle pin on the current window (Cmd+P)
    func togglePinCurrentWindow() {
        guard let focusedId = lastFocusedWindowId else { return }
        togglePin(id: focusedId)
    }

    // MARK: - Window Management

    func showWindow(id: UUID) {
        guard let window = nsWindows[id] else { return }

        NSApp.activate(ignoringOtherApps: true)

        if window.isMiniaturized {
            window.deminiaturize(nil)
        }

        window.makeKeyAndOrderFront(nil)
        lastFocusedWindowId = id
    }

    func closeWindow(id: UUID) {
        guard let window = nsWindows[id] else { return }
        window.close() // triggers delegate → cleanup
    }

    func togglePin(id: UUID) {
        guard let state = windowStates[id], let window = nsWindows[id] else { return }
        state.isPinned.toggle()
        window.level = state.isPinned ? .floating : .normal
    }

    func setWindowPinned(id: UUID, pinned: Bool) {
        guard let state = windowStates[id], let window = nsWindows[id] else { return }
        state.isPinned = pinned
        window.level = pinned ? .floating : .normal
    }

    func focusAllWindows() {
        guard !nsWindows.isEmpty else { return }
        NSApp.activate(ignoringOtherApps: true)

        for (_, window) in nsWindows {
            if window.isMiniaturized {
                window.deminiaturize(nil)
            }
            window.orderFront(nil)
        }

        if let lastId = lastFocusedWindowId, let window = nsWindows[lastId] {
            window.makeKeyAndOrderFront(nil)
        }
    }

    func saveAllWindows() {
        for (_, state) in windowStates {
            state.saveNow()
        }
    }

    func updateWindowTitle(id: UUID) {
        guard let state = windowStates[id], let window = nsWindows[id] else { return }
        let title = state.note.title.isEmpty ? state.note.autoGeneratedTitle : state.note.title
        window.title = title // kept for accessibility & Dock
        titleViews[id]?.displayTitle = title
        // Re-hide the native title field; AppKit can restore it after window.title changes.
        if let container = findTitlebarContainer(in: window),
           let nativeField = findNativeTitleField(in: container) {
            nativeField.isHidden = true
        }
    }

    // MARK: - Lifecycle (called by delegate)

    fileprivate func windowDidBecomeKey(id: UUID) {
        lastFocusedWindowId = id
    }

    fileprivate func windowWillClose(id: UUID) {
        windowStates[id]?.cleanup()
        windowStates.removeValue(forKey: id)
        windowDelegates.removeValue(forKey: id)
        titleViews.removeValue(forKey: id)
        nsWindows[id]?.contentViewController = nil
        nsWindows.removeValue(forKey: id)

        if lastFocusedWindowId == id {
            lastFocusedWindowId = windowStates.keys.first
        }
    }

    // MARK: - Private: Panel Construction

    private func createPanel(windowId: UUID, state: ZettelWindowState) -> ZettelPanel {
        // Build SwiftUI view
        let editorView = ZettelEditorView(state: state)
        let hostingController = NSHostingController(rootView: editorView)

        // Calculate position
        let defaultSize = NSSize(width: 640, height: 520)
        let initialRect = centeredRect(size: defaultSize, cascadeIndex: windowStates.count)

        // Create panel — Liquid Glass chrome on macOS Tahoe
        let panel = ZettelPanel(
            contentRect: initialRect,
            styleMask: [.titled, .closable, .miniaturizable, .resizable, .fullSizeContentView],
            backing: .buffered,
            defer: false
        )

        panel.animationBehavior = .documentWindow
        panel.becomesKeyOnlyIfNeeded = false
        panel.hidesOnDeactivate = false
        panel.worksWhenModal = true
        panel.isReleasedWhenClosed = false
        panel.isMovableByWindowBackground = true
        panel.toolbarStyle = .unified

        // Titlebar: transparent glass — content extends underneath
        panel.titlebarAppearsTransparent = true
        panel.titleVisibility = .visible // kept for correct toolbar layout; native field is hidden below

        // Transparent background for Liquid Glass
        panel.isOpaque = false
        panel.backgroundColor = .clear

        // Set min size
        panel.minSize = NSSize(width: 560, height: 420)

        // Title
        let title = state.note.title.isEmpty ? state.note.autoGeneratedTitle : state.note.title
        panel.title = title

        panel.contentViewController = hostingController

        // Delegate
        let delegate = ZettelWindowDelegate(windowId: windowId, manager: self)
        windowDelegates[windowId] = delegate
        panel.delegate = delegate

        // Install custom click-to-edit title view
        setupCustomTitle(windowId: windowId, state: state, panel: panel)

        return panel
    }

    private func setupCustomTitle(windowId: UUID, state: ZettelWindowState, panel: NSWindow) {
        guard let container = findTitlebarContainer(in: panel) else { return }

        // Hide the native title NSTextField so it doesn't occupy space,
        // while keeping titleVisibility = .visible for correct toolbar layout.
        if let nativeField = findNativeTitleField(in: container) {
            nativeField.isHidden = true
        }

        let displayTitle = state.note.title.isEmpty ? state.note.autoGeneratedTitle : state.note.title
        let titleView = TitlebarTitleView()
        titleView.displayTitle = displayTitle
        titleView.onCommit = { [weak self] newTitle in
            guard let self else { return }
            state.updateTitle(newTitle)
            self.updateWindowTitle(id: windowId)
        }
        titleViews[windowId] = titleView

        titleView.translatesAutoresizingMaskIntoConstraints = false
        container.addSubview(titleView)
        NSLayoutConstraint.activate([
            titleView.centerXAnchor.constraint(equalTo: container.centerXAnchor),
            titleView.centerYAnchor.constraint(equalTo: container.centerYAnchor),
            titleView.heightAnchor.constraint(equalTo: container.heightAnchor),
            // Cap to half the container so it never overlaps the buttons on either side.
            titleView.widthAnchor.constraint(lessThanOrEqualTo: container.widthAnchor, multiplier: 0.5),
            // Minimum so the view is always visible for short titles.
            titleView.widthAnchor.constraint(greaterThanOrEqualToConstant: 60),
        ])
    }

    /// Finds the titlebar container view (NSTitlebarView).
    private func findTitlebarContainer(in window: NSWindow) -> NSView? {
        guard let themeFrame = window.contentView?.superview else { return nil }
        return searchTitlebarContainer(in: themeFrame)
    }

    private func searchTitlebarContainer(in view: NSView) -> NSView? {
        let name = String(describing: type(of: view))
        if name.contains("NSTitlebarView") { return view }
        for sub in view.subviews {
            if let found = searchTitlebarContainer(in: sub) { return found }
        }
        return nil
    }

    /// Finds the NSTextField that AppKit uses for the window title inside the titlebar container.
    private func findNativeTitleField(in container: NSView) -> NSTextField? {
        for sub in container.subviews {
            if let tf = sub as? NSTextField { return tf }
            if let found = findNativeTitleField(in: sub) { return found }
        }
        return nil
    }

    private func centeredRect(size: NSSize, cascadeIndex: Int) -> NSRect {
        let mouse = NSEvent.mouseLocation
        let screen = NSScreen.screens.first { NSMouseInRect(mouse, $0.frame, false) } ?? NSScreen.main

        guard let s = screen else {
            return NSRect(origin: .zero, size: size)
        }

        let vf = s.visibleFrame
        let cascadeOffset = CGFloat(cascadeIndex) * 25.0

        var origin = NSPoint(
            x: vf.midX - size.width / 2 + cascadeOffset,
            y: vf.midY - size.height / 2 - cascadeOffset
        )

        // Keep within visible frame
        if origin.x + size.width > vf.maxX { origin.x = vf.minX + 50 }
        if origin.y < vf.minY { origin.y = vf.maxY - size.height - 50 }

        return NSRect(origin: origin, size: size)
    }
}

// MARK: - Window Delegate

@MainActor
private final class ZettelWindowDelegate: NSObject, NSWindowDelegate {
    let windowId: UUID
    weak var manager: ZettelWindowManager?

    init(windowId: UUID, manager: ZettelWindowManager) {
        self.windowId = windowId
        self.manager = manager
        super.init()
    }

    func windowDidBecomeKey(_ notification: Notification) {
        manager?.windowDidBecomeKey(id: windowId)
    }

    func windowWillClose(_ notification: Notification) {
        manager?.windowWillClose(id: windowId)
    }
}

// MARK: - Custom Click-to-Edit Title View

/// A compact label in the titlebar that becomes an editable text field on click.
/// This keeps the surrounding titlebar area draggable by only spanning the text width.
@MainActor
private final class TitlebarTitleView: NSView, NSTextFieldDelegate {

    private let textField = NSTextField()
    private var editingInProgress = false

    /// Called when the user commits a new title. Pass the trimmed new value.
    var onCommit: ((String) -> Void)?

    /// The title currently displayed. Updating this resizes the view automatically.
    var displayTitle: String = "" {
        didSet {
            textField.stringValue = displayTitle
        }
    }

    override init(frame: NSRect) {
        super.init(frame: frame)
        setup()
    }
    required init?(coder: NSCoder) { fatalError() }

    private func setup() {
        textField.isBezeled = false
        textField.drawsBackground = false
        textField.isEditable = false
        textField.isSelectable = false
        textField.alignment = .center
        textField.usesSingleLineMode = true
        textField.lineBreakMode = .byTruncatingMiddle
        textField.focusRingType = .none
        textField.cell?.isScrollable = false
        textField.cell?.wraps = false
        textField.font = .systemFont(ofSize: 13, weight: .semibold)
        textField.delegate = self
        textField.translatesAutoresizingMaskIntoConstraints = false
        addSubview(textField)
        NSLayoutConstraint.activate([
            textField.centerXAnchor.constraint(equalTo: centerXAnchor),
            textField.centerYAnchor.constraint(equalTo: centerYAnchor),
            textField.widthAnchor.constraint(equalTo: widthAnchor),
        ])
    }

    // MARK: - Sizing

    // No intrinsicContentSize override — returning noIntrinsicMetric for width
    // prevents the titlebar from ever resizing the window to fit the title text.
    // The view expands to fill available space (up to the lessThanOrEqualTo cap)
    // and the text field truncates within it.

    // MARK: - Click handling

    override func mouseDown(with event: NSEvent) {
        if !editingInProgress {
            editingInProgress = true
            textField.isEditable = true
            textField.isSelectable = true
            textField.cell?.isScrollable = true  // allow scrolling while editing long titles
            window?.makeFirstResponder(textField)
            textField.mouseDown(with: event)
        } else {
            super.mouseDown(with: event)
        }
    }

    private func endEditing(commit: Bool) {
        guard editingInProgress else { return }
        editingInProgress = false
        textField.isEditable = false
        textField.isSelectable = false
        textField.cell?.isScrollable = false  // back to truncation display mode
        if commit {
            let trimmed = textField.stringValue.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.isEmpty { onCommit?(trimmed) }
        } else {
            // Revert to last known good title
            textField.stringValue = displayTitle
        }
        window?.makeFirstResponder(nil)
    }

    // MARK: - NSTextFieldDelegate

    func control(_ control: NSControl, textView: NSTextView, doCommandBy commandSelector: Selector) -> Bool {
        if commandSelector == #selector(NSResponder.insertNewline(_:)) {
            endEditing(commit: true)
            return true
        }
        if commandSelector == #selector(NSResponder.cancelOperation(_:)) {
            endEditing(commit: false)
            return true
        }
        return false
    }

    func controlTextDidEndEditing(_ obj: Notification) {
        endEditing(commit: true)
    }
}
