//
//  ZettelWindowState.swift
//  ZettelMac
//
//  Per-window state container. Each Zettel window owns one of these.
//

import Foundation
import ZettelKit
import Combine

/// Per-window state. Manages note data, auto-save, and UI state for a single Zettel window.
@MainActor @Observable
final class ZettelWindowState {
    let windowId: UUID

    /// The note currently being edited in this window
    var note: Note

    /// The filename on disk (for rename tracking)
    var persistedFilename: String?

    /// Whether the note has unsaved changes
    var isDirty: Bool = false

    /// Whether this window is pinned (floating)
    var isPinned: Bool = false

    /// Whether the sidebar is visible
    var isSidebarVisible: Bool = false

    /// Set to `true` to request the new-note genie animation from the view.
    /// The view resets this to `false` once it starts the animation.
    var newNoteAnimationRequested: Bool = false

    /// Auto-save debounce
    private var autoSaveTask: Task<Void, Never>?
    private let autoSaveInterval: TimeInterval = 1.5

    /// Observer for external file changes on disk
    private var fileChangeObserver: (any NSObjectProtocol)?

    init(windowId: UUID = UUID(), note: Note? = nil) {
        self.windowId = windowId
        if let note = note {
            self.note = note
            self.persistedFilename = note.filename
        } else {
            // New empty note with auto-generated title
            var newNote = Note(title: "", content: "")
            newNote.title = newNote.autoGeneratedTitle
            self.note = newNote
            self.persistedFilename = nil
        }

        setupFileChangeObserver()
    }

    // MARK: - External File Change Handling

    /// Listen for file content changes on disk and update if they
    /// affect the note currently open in this window.
    private func setupFileChangeObserver() {
        fileChangeObserver = NotificationCenter.default.addObserver(
            forName: .noteFileDidChangeOnDisk,
            object: nil,
            queue: .main
        ) { [weak self] notification in
            // Extract Sendable values before crossing isolation boundary
            let filename = notification.userInfo?["filename"] as? String
            let content = notification.userInfo?["content"] as? String
            let title = notification.userInfo?["title"] as? String
            let modifiedAt = notification.userInfo?["modifiedAt"] as? Date
            Task { @MainActor in
                self?.handleExternalFileChange(
                    filename: filename,
                    content: content,
                    title: title,
                    modifiedAt: modifiedAt
                )
            }
        }
    }

    /// Applies external content update without marking the note dirty.
    private func handleExternalFileChange(
        filename: String?,
        content: String?,
        title: String?,
        modifiedAt: Date?
    ) {
        guard let filename, filename == persistedFilename,
              let content else {
            return
        }

        // Don't overwrite if user has pending unsaved edits
        // (auto-save will reconcile later)
        guard !isDirty else { return }

        // Update note content from disk without triggering auto-save
        note.content = content
        if let modifiedAt {
            note.modifiedAt = modifiedAt
        }
        if let title, title != note.title {
            note.title = title
        }
    }

    // MARK: - Content Updates

    func updateTitle(_ newTitle: String) {
        guard note.title != newTitle else { return }
        note.updateTitle(newTitle)
        isDirty = true
        scheduleAutoSave()
    }

    func updateContent(_ newContent: String) {
        guard note.content != newContent else { return }
        note.updateContent(newContent)
        isDirty = true
        scheduleAutoSave()
    }

    // MARK: - Save

    func saveNow() {
        autoSaveTask?.cancel()
        autoSaveTask = nil
        guard isDirty else { return }

        let savedFilename = MacNoteStore.shared.saveNote(note, originalFilename: persistedFilename)
        if let savedFilename {
            persistedFilename = savedFilename
            isDirty = false
        }
    }

    func scheduleAutoSave() {
        autoSaveTask?.cancel()
        autoSaveTask = Task { [weak self] in
            try? await Task.sleep(for: .seconds(self?.autoSaveInterval ?? 1.5))
            guard !Task.isCancelled else { return }
            self?.saveNow()
        }
    }

    // MARK: - Note Management

    /// Replace current note with a different one (from picker).
    /// If the note is a cloud stub, triggers download and updates once available.
    func loadNote(_ newNote: Note) {
        saveNow() // flush pending save first

        if newNote.isCloudStub {
            // Show placeholder immediately
            var placeholder = newNote
            placeholder.content = "Loading from iCloud…"
            note = placeholder
            persistedFilename = newNote.filename
            isDirty = false

            // Download in background, then swap in the real content
            Task { [weak self] in
                guard let self else { return }
                do {
                    let downloaded = try await MacNoteStore.shared.downloadCloudFile(for: newNote)
                    self.note = downloaded
                    self.persistedFilename = downloaded.filename
                    self.isDirty = false
                } catch {
                    var errorNote = newNote
                    errorNote.content = "Failed to load from iCloud: \(error.localizedDescription)"
                    errorNote.isCloudStub = false
                    errorNote.isDownloading = false
                    self.note = errorNote
                }
            }
        } else {
            note = newNote
            persistedFilename = newNote.filename
            isDirty = false
        }
    }

    /// Clear to a fresh empty note
    func clearToNewNote() {
        saveNow()
        var newNote = Note(title: "", content: "")
        newNote.title = newNote.autoGeneratedTitle
        note = newNote
        persistedFilename = nil
        isDirty = false
    }

    /// Reset to a fresh empty note WITHOUT saving the current one.
    /// Used when the active note has been externally deleted (e.g. via the picker).
    func resetToNewNote() {
        autoSaveTask?.cancel()
        autoSaveTask = nil
        var newNote = Note(title: "", content: "")
        newNote.title = newNote.autoGeneratedTitle
        note = newNote
        persistedFilename = nil
        isDirty = false
    }

    /// Cleanup on window close
    func cleanup() {
        saveNow()
        autoSaveTask?.cancel()
        autoSaveTask = nil
        if let observer = fileChangeObserver {
            NotificationCenter.default.removeObserver(observer)
            fileChangeObserver = nil
        }
    }
}
