//
//  ZettelWindowState.swift
//  ZettelMac
//
//  Per-window state container. Each Zettel window owns one of these.
//

import Foundation
import ZettelKit
import Combine

/// Per-window state. Manages note data, auto-save, and UI state for a single Zettel window.
@MainActor @Observable
final class ZettelWindowState {
    let windowId: UUID

    /// The note currently being edited in this window
    var note: Note

    /// The filename on disk (for rename tracking)
    var persistedFilename: String?

    /// Whether the note has unsaved changes
    var isDirty: Bool = false

    /// Whether this window is pinned (floating)
    var isPinned: Bool = false

    /// Whether the note picker modal is showing
    var isShowingPicker: Bool = false

    /// Set to `true` to request the new-note genie animation from the view.
    /// The view resets this to `false` once it starts the animation.
    var newNoteAnimationRequested: Bool = false

    /// Auto-save debounce
    private var autoSaveTask: Task<Void, Never>?
    private let autoSaveInterval: TimeInterval = 1.5

    init(windowId: UUID = UUID(), note: Note? = nil) {
        self.windowId = windowId
        if let note = note {
            self.note = note
            self.persistedFilename = note.filename
        } else {
            // New empty note with auto-generated title
            var newNote = Note(title: "", content: "")
            newNote.title = newNote.autoGeneratedTitle
            self.note = newNote
            self.persistedFilename = nil
        }
    }

    // MARK: - Content Updates

    func updateTitle(_ newTitle: String) {
        guard note.title != newTitle else { return }
        note.updateTitle(newTitle)
        isDirty = true
        scheduleAutoSave()
    }

    func updateContent(_ newContent: String) {
        guard note.content != newContent else { return }
        note.updateContent(newContent)
        isDirty = true
        scheduleAutoSave()
    }

    // MARK: - Save

    func saveNow() {
        autoSaveTask?.cancel()
        autoSaveTask = nil
        guard isDirty else { return }

        let savedFilename = MacNoteStore.shared.saveNote(note, originalFilename: persistedFilename)
        if let savedFilename {
            persistedFilename = savedFilename
            isDirty = false
        }
    }

    func scheduleAutoSave() {
        autoSaveTask?.cancel()
        autoSaveTask = Task { [weak self] in
            try? await Task.sleep(for: .seconds(self?.autoSaveInterval ?? 1.5))
            guard !Task.isCancelled else { return }
            self?.saveNow()
        }
    }

    // MARK: - Note Management

    /// Replace current note with a different one (from picker)
    func loadNote(_ newNote: Note) {
        saveNow() // flush pending save first
        note = newNote
        persistedFilename = newNote.filename
        isDirty = false
        isShowingPicker = false
    }

    /// Clear to a fresh empty note
    func clearToNewNote() {
        saveNow()
        var newNote = Note(title: "", content: "")
        newNote.title = newNote.autoGeneratedTitle
        note = newNote
        persistedFilename = nil
        isDirty = false
    }

    /// Cleanup on window close
    func cleanup() {
        saveNow()
        autoSaveTask?.cancel()
        autoSaveTask = nil
    }
}
