//
//  ZettelWindowState.swift
//  ZettelMac
//
//  Per-window state container. Each Zettel window owns one of these.
//

import Foundation
import ZettelKit
import Combine

/// Per-window state. Manages note data, auto-save, and UI state for a single Zettel window.
@MainActor @Observable
final class ZettelWindowState {
    let windowId: UUID

    /// The note currently being edited in this window
    var note: Note

    /// The filename on disk (for rename tracking)
    var persistedFilename: String?

    /// Whether the note has unsaved changes
    var isDirty: Bool = false

    /// Whether this window is pinned (floating)
    var isPinned: Bool = false

    /// Whether the sidebar is visible
    var isSidebarVisible: Bool = false

    /// Set to `true` to request the new-note slide animation from the view.
    /// The view resets this to `false` once it starts the animation.
    var newNoteAnimationRequested: Bool = false

    /// Set to `true` to request the open-from-sidebar slide-in animation.
    /// The view resets this to `false` once it starts the animation.
    var openNoteAnimationRequested: Bool = false

    /// The note to open (set before `openNoteAnimationRequested`).
    var openNoteValue: Note? = nil

    /// The title currently shown in the `.principal` toolbar item.
    /// Updated instantly or via the split-flap animation.
    var displayTitle: String = ""

    // MARK: - Title Animation (split-flap)

    private var flipTask: Task<Void, Never>?
    private var _isFlipAnimating = false

    /// Auto-save debounce
    private var autoSaveTask: Task<Void, Never>?
    private let autoSaveInterval: TimeInterval = 1.5

    /// Observer for external file changes on disk
    private var fileChangeObserver: (any NSObjectProtocol)?

    /// Observer for storage directory changes
    private var directoryChangeObserver: (any NSObjectProtocol)?

    init(windowId: UUID = UUID(), note: Note? = nil) {
        self.windowId = windowId
        if let note = note {
            self.note = note
            self.persistedFilename = note.filename
        } else {
            // New empty note with auto-generated title
            var newNote = Note(title: "", content: "")
            newNote.title = newNote.autoGeneratedTitle
            self.note = newNote
            self.persistedFilename = nil
        }
        self.displayTitle = self.note.title.isEmpty ? self.note.autoGeneratedTitle : self.note.title

        setupFileChangeObserver()
        setupDirectoryChangeObserver()
    }

    // MARK: - Title Display

    /// Instantly sets the displayed title without animation.
    func setDisplayTitle(_ title: String) {
        guard !_isFlipAnimating else { return }
        displayTitle = title
    }

    /// Animates the toolbar title to `newTitle` using a split-flap effect.
    func animateTitle(to newTitle: String, duration: TimeInterval = 0.35) {
        if _isFlipAnimating && newTitle == displayTitle { return }
        if !_isFlipAnimating && displayTitle == newTitle { return }

        flipTask?.cancel()
        flipTask = nil

        let oldDisplay = displayTitle
        let targetChars = Array(newTitle)
        let oldCount = oldDisplay.count
        let targetCount = targetChars.count

        guard targetCount > 0 else {
            _isFlipAnimating = false
            displayTitle = newTitle
            return
        }

        _isFlipAnimating = true
        displayTitle = newTitle   // semantic value (guards duplicate calls)

        let tickMs: UInt64 = 30
        let totalTicks = max(Int(duration / (Double(tickMs) / 1000.0)), 1)
        let flipChars: [Character] = Array("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/:.-\u{2013}")

        flipTask = Task { @MainActor [weak self] in
            for tick in 0...totalTicks {
                guard !Task.isCancelled, let self else { return }
                let progress = Double(tick) / Double(totalTicks)
                let currentLength = max(oldCount + Int(round(progress * Double(targetCount - oldCount))), 0)
                var display = [Character]()
                for i in 0..<currentLength {
                    let threshold = targetCount > 1
                        ? 0.15 + (Double(i) / Double(targetCount - 1)) * 0.70
                        : 0.5
                    if i < targetCount, progress >= threshold {
                        display.append(targetChars[i])
                    } else if i < targetCount, targetChars[i] == " " {
                        display.append(" ")
                    } else {
                        display.append(flipChars.randomElement()!)
                    }
                }
                self.displayTitle = String(display)
                try? await Task.sleep(for: .milliseconds(tickMs))
            }
            guard !Task.isCancelled, let self else { return }
            self.displayTitle = newTitle
            self._isFlipAnimating = false
        }
    }

    // MARK: - External File Change Handling

    /// Listen for file content changes on disk and update if they
    /// affect the note currently open in this window.
    private func setupFileChangeObserver() {
        fileChangeObserver = NotificationCenter.default.addObserver(
            forName: .noteFileDidChangeOnDisk,
            object: nil,
            queue: .main
        ) { [weak self] notification in
            // Extract Sendable values before crossing isolation boundary
            let filename = notification.userInfo?["filename"] as? String
            let content = notification.userInfo?["content"] as? String
            let title = notification.userInfo?["title"] as? String
            let modifiedAt = notification.userInfo?["modifiedAt"] as? Date
            Task { @MainActor in
                self?.handleExternalFileChange(
                    filename: filename,
                    content: content,
                    title: title,
                    modifiedAt: modifiedAt
                )
            }
        }
    }

    /// Applies external content update without marking the note dirty.
    private func handleExternalFileChange(
        filename: String?,
        content: String?,
        title: String?,
        modifiedAt: Date?
    ) {
        guard let filename, filename == persistedFilename,
              let content else {
            return
        }

        // Don't overwrite if user has pending unsaved edits
        // (auto-save will reconcile later)
        guard !isDirty else { return }

        // Update note content from disk without triggering auto-save
        note.content = content
        if let modifiedAt {
            note.modifiedAt = modifiedAt
        }
        if let title, title != note.title {
            note.title = title
        }
    }

    // MARK: - Storage Directory Change

    /// Listen for storage directory changes and reset to a fresh note.
    private func setupDirectoryChangeObserver() {
        directoryChangeObserver = NotificationCenter.default.addObserver(
            forName: .storageDirectoryDidChange,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            Task { @MainActor in
                self?.handleDirectoryChange()
            }
        }
    }

    /// Flush any pending save and reset to a blank note.
    private func handleDirectoryChange() {
        // Flush any in-flight auto-save for the old directory
        saveNow()
        // Reset to a fresh note (no save — old directory is gone)
        resetToNewNote()
        animateTitle(to: note.title)
    }

    // MARK: - Content Updates

    func updateTitle(_ newTitle: String) {
        guard note.title != newTitle else { return }
        note.updateTitle(newTitle)
        isDirty = true
        scheduleAutoSave()
    }

    func updateContent(_ newContent: String) {
        guard note.content != newContent else { return }
        note.updateContent(newContent)
        isDirty = true
        scheduleAutoSave()
    }

    // MARK: - Save

    func saveNow() {
        autoSaveTask?.cancel()
        autoSaveTask = nil
        guard isDirty else { return }

        let savedFilename = MacNoteStore.shared.saveNote(note, originalFilename: persistedFilename)
        if let savedFilename {
            persistedFilename = savedFilename
            isDirty = false
        }
    }

    func scheduleAutoSave() {
        autoSaveTask?.cancel()
        autoSaveTask = Task { [weak self] in
            try? await Task.sleep(for: .seconds(self?.autoSaveInterval ?? 1.5))
            guard !Task.isCancelled else { return }
            self?.saveNow()
        }
    }

    // MARK: - Note Management

    /// Replace current note with a different one (from picker).
    /// If the note is a cloud stub, triggers download and updates once available.
    func loadNote(_ newNote: Note) {
        saveNow() // flush pending save first

        if newNote.isCloudStub {
            // Show placeholder immediately
            var placeholder = newNote
            placeholder.content = "Loading from iCloud…"
            note = placeholder
            persistedFilename = newNote.filename
            isDirty = false

            // Download in background, then swap in the real content
            Task { [weak self] in
                guard let self else { return }
                do {
                    let downloaded = try await MacNoteStore.shared.downloadCloudFile(for: newNote)
                    self.note = downloaded
                    self.persistedFilename = downloaded.filename
                    self.isDirty = false
                } catch {
                    var errorNote = newNote
                    errorNote.content = "Failed to load from iCloud: \(error.localizedDescription)"
                    errorNote.isCloudStub = false
                    errorNote.isDownloading = false
                    self.note = errorNote
                }
            }
        } else {
            note = newNote
            persistedFilename = newNote.filename
            isDirty = false
        }
    }

    /// Clear to a fresh empty note
    func clearToNewNote() {
        saveNow()
        var newNote = Note(title: "", content: "")
        newNote.title = newNote.autoGeneratedTitle
        note = newNote
        persistedFilename = nil
        isDirty = false
    }

    /// Reset to a fresh empty note WITHOUT saving the current one.
    /// Used when the active note has been externally deleted (e.g. via the picker).
    func resetToNewNote() {
        autoSaveTask?.cancel()
        autoSaveTask = nil
        var newNote = Note(title: "", content: "")
        newNote.title = newNote.autoGeneratedTitle
        note = newNote
        persistedFilename = nil
        isDirty = false
    }

    /// Cleanup on window close
    func cleanup() {
        saveNow()
        flipTask?.cancel()
        flipTask = nil
        autoSaveTask?.cancel()
        autoSaveTask = nil
        if let observer = fileChangeObserver {
            NotificationCenter.default.removeObserver(observer)
            fileChangeObserver = nil
        }
        if let observer = directoryChangeObserver {
            NotificationCenter.default.removeObserver(observer)
            directoryChangeObserver = nil
        }
    }
}
