//
//  ZettelWindowManager.swift
//  ZettelMac
//
//  Manages multiple Zettel note windows.
//  Each window is an NSPanel hosting a ZettelEditorView with its own state.
//

import AppKit
import SwiftUI
import ZettelKit

/// Manages all Zettel note windows — creation, focus, pinning, and lifecycle.
@MainActor
final class ZettelWindowManager: NSObject, ObservableObject {
    static let shared = ZettelWindowManager()

    // MARK: - State

    /// All active window states keyed by window ID
    private(set) var windowStates: [UUID: ZettelWindowState] = [:]

    /// NSWindow references keyed by window ID
    private var nsWindows: [UUID: NSWindow] = [:]

    /// Delegates kept alive keyed by window ID
    private var windowDelegates: [UUID: ZettelWindowDelegate] = [:]

    /// Last focused window (for keyboard shortcut routing)
    private(set) var lastFocusedWindowId: UUID?

    private override init() {
        super.init()
    }

    // MARK: - Window Creation

    /// Create a new Zettel window, optionally preloaded with a note.
    @discardableResult
    func createWindow(note: Note? = nil) -> UUID {
        let windowId = UUID()
        let state = ZettelWindowState(windowId: windowId, note: note)
        windowStates[windowId] = state

        let panel = createPanel(windowId: windowId, state: state)
        nsWindows[windowId] = panel

        showWindow(id: windowId)
        
        // Ensure notes are loaded
        Task {
            await MacNoteStore.shared.loadAllNotes()
        }

        return windowId
    }

    // MARK: - Actions (dispatched from menu commands)

    /// New note in the currently focused window (Cmd+N)
    func newNoteInCurrentWindow() {
        if let focusedId = lastFocusedWindowId, let state = windowStates[focusedId] {
            state.clearToNewNote()
            updateWindowTitle(id: focusedId)
        } else {
            createWindow()
        }
    }

    /// Toggle the note picker in the current window (Cmd+O)
    func togglePickerInCurrentWindow() {
        if let focusedId = lastFocusedWindowId, let state = windowStates[focusedId] {
            state.isShowingPicker.toggle()
        }
    }

    /// Toggle pin on the current window (Cmd+P)
    func togglePinCurrentWindow() {
        guard let focusedId = lastFocusedWindowId else { return }
        togglePin(id: focusedId)
    }

    // MARK: - Window Management

    func showWindow(id: UUID) {
        guard let window = nsWindows[id] else { return }

        NSApp.activate(ignoringOtherApps: true)

        if window.isMiniaturized {
            window.deminiaturize(nil)
        }

        window.makeKeyAndOrderFront(nil)
        lastFocusedWindowId = id
    }

    func closeWindow(id: UUID) {
        guard let window = nsWindows[id] else { return }
        window.close() // triggers delegate → cleanup
    }

    func togglePin(id: UUID) {
        guard let state = windowStates[id], let window = nsWindows[id] else { return }
        state.isPinned.toggle()
        window.level = state.isPinned ? .floating : .normal
    }

    func setWindowPinned(id: UUID, pinned: Bool) {
        guard let state = windowStates[id], let window = nsWindows[id] else { return }
        state.isPinned = pinned
        window.level = pinned ? .floating : .normal
    }

    func focusAllWindows() {
        guard !nsWindows.isEmpty else { return }
        NSApp.activate(ignoringOtherApps: true)

        for (_, window) in nsWindows {
            if window.isMiniaturized {
                window.deminiaturize(nil)
            }
            window.orderFront(nil)
        }

        if let lastId = lastFocusedWindowId, let window = nsWindows[lastId] {
            window.makeKeyAndOrderFront(nil)
        }
    }

    func saveAllWindows() {
        for (_, state) in windowStates {
            state.saveNow()
        }
    }

    func updateWindowTitle(id: UUID) {
        guard let state = windowStates[id], let window = nsWindows[id] else { return }
        let title = state.note.title.isEmpty ? state.note.autoGeneratedTitle : state.note.title
        window.title = title
    }

    // MARK: - Lifecycle (called by delegate)

    fileprivate func windowDidBecomeKey(id: UUID) {
        lastFocusedWindowId = id
    }

    fileprivate func windowWillClose(id: UUID) {
        windowStates[id]?.cleanup()
        windowStates.removeValue(forKey: id)
        windowDelegates.removeValue(forKey: id)
        nsWindows[id]?.contentViewController = nil
        nsWindows.removeValue(forKey: id)

        if lastFocusedWindowId == id {
            lastFocusedWindowId = windowStates.keys.first
        }
    }

    // MARK: - Private: Panel Construction

    private func createPanel(windowId: UUID, state: ZettelWindowState) -> ZettelPanel {
        // Build SwiftUI view
        let editorView = ZettelEditorView(state: state)
        let hostingController = NSHostingController(rootView: editorView)

        // Calculate position
        let defaultSize = NSSize(width: 640, height: 520)
        let initialRect = centeredRect(size: defaultSize, cascadeIndex: windowStates.count)

        // Create panel — standard macOS window chrome (system handles glass)
        let panel = ZettelPanel(
            contentRect: initialRect,
            styleMask: [.titled, .closable, .miniaturizable, .resizable],
            backing: .buffered,
            defer: false
        )

        panel.animationBehavior = .documentWindow
        panel.becomesKeyOnlyIfNeeded = false
        panel.hidesOnDeactivate = false
        panel.worksWhenModal = true
        panel.isReleasedWhenClosed = false
        panel.isMovableByWindowBackground = true

        // Titlebar: visible, standard (system provides liquid glass chrome)
        panel.titleVisibility = .visible

        // Set min size
        panel.minSize = NSSize(width: 320, height: 280)

        // Title
        let title = state.note.title.isEmpty ? state.note.autoGeneratedTitle : state.note.title
        panel.title = title

        panel.contentViewController = hostingController

        // Delegate
        let delegate = ZettelWindowDelegate(windowId: windowId, manager: self)
        windowDelegates[windowId] = delegate
        panel.delegate = delegate

        return panel
    }

    private func centeredRect(size: NSSize, cascadeIndex: Int) -> NSRect {
        let mouse = NSEvent.mouseLocation
        let screen = NSScreen.screens.first { NSMouseInRect(mouse, $0.frame, false) } ?? NSScreen.main

        guard let s = screen else {
            return NSRect(origin: .zero, size: size)
        }

        let vf = s.visibleFrame
        let cascadeOffset = CGFloat(cascadeIndex) * 25.0

        var origin = NSPoint(
            x: vf.midX - size.width / 2 + cascadeOffset,
            y: vf.midY - size.height / 2 - cascadeOffset
        )

        // Keep within visible frame
        if origin.x + size.width > vf.maxX { origin.x = vf.minX + 50 }
        if origin.y < vf.minY { origin.y = vf.maxY - size.height - 50 }

        return NSRect(origin: origin, size: size)
    }
}

// MARK: - Window Delegate

@MainActor
private final class ZettelWindowDelegate: NSObject, NSWindowDelegate {
    let windowId: UUID
    weak var manager: ZettelWindowManager?

    init(windowId: UUID, manager: ZettelWindowManager) {
        self.windowId = windowId
        self.manager = manager
        super.init()
    }

    func windowDidBecomeKey(_ notification: Notification) {
        manager?.windowDidBecomeKey(id: windowId)
    }

    func windowWillClose(_ notification: Notification) {
        manager?.windowWillClose(id: windowId)
    }
}
