//
//  NotePicker.swift
//  ZettelMac
//
//  Anchored popup for browsing and opening notes.
//  Cmd+Click opens in a new window.
//

import AppKit
import SwiftUI
import ZettelKit

struct NotePicker: View {
    @Bindable var state: ZettelWindowState

    @State private var searchText = ""

    private var store: MacNoteStore { MacNoteStore.shared }

    private var filteredNotes: [Note] {
        if searchText.isEmpty {
            return store.allNotes
        }
        return store.allNotes.filter { note in
            note.title.localizedStandardContains(searchText)
            || note.content.localizedStandardContains(searchText)
        }
    }

    var body: some View {
        VStack(spacing: 10) {
            searchField

            if store.isLoading {
                ProgressView()
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else if filteredNotes.isEmpty {
                emptyState
            } else {
                notesList
            }
        }
        .frame(width: 420, height: 260)
        .padding(12)
        .background(.regularMaterial)
        .task {
            await store.loadAllNotes()
        }
        .onKeyPress(.escape) {
            state.isShowingPicker = false
            return .handled
        }
    }

    // MARK: - Search Field

    private var searchField: some View {
        HStack {
            TextField(
                String(
                    localized: "mac.picker.filter_placeholder",
                    defaultValue: "Filter notes…",
                    comment: "Picker search placeholder"
                ),
                text: $searchText
            )
            .textFieldStyle(.roundedBorder)
            .font(.system(size: 15))

            if !searchText.isEmpty {
                Button {
                    searchText = ""
                } label: {
                    Image(systemName: "xmark.circle.fill")
                        .foregroundStyle(.secondary)
                        .font(.system(size: 12))
                }
                .buttonStyle(.plain)
            }
        }
    }

    // MARK: - Notes List

    private var notesList: some View {
        ScrollView {
            LazyVStack(spacing: 4) {
                ForEach(filteredNotes, id: \.id) { note in
                    NotePickerRow(
                        note: note,
                        onOpen: { openNoteFromClick(note) },
                        onDelete: { deleteNote(note) }
                    )
                }
            }
            .padding(.vertical, 2)
        }
    }

    // MARK: - Empty State

    private var emptyState: some View {
        VStack(spacing: 8) {
            Image(systemName: "note.text")
                .font(.system(size: 28))
                .foregroundStyle(.tertiary)
            Text(searchText.isEmpty
                 ? String(localized: "mac.picker.empty", defaultValue: "No notes yet", comment: "Picker empty state")
                 : String(localized: "mac.picker.no_results", defaultValue: "No matching notes", comment: "Picker no results"))
                .foregroundStyle(.secondary)
                .font(.system(size: 13))
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    // MARK: - Actions

    private func openNoteFromClick(_ note: Note) {
        let openInNewWindow = NSApp.currentEvent?.modifierFlags.contains(.command) == true
        openNote(note, inNewWindow: openInNewWindow)
    }

    private func openNote(_ note: Note, inNewWindow: Bool) {
        if inNewWindow {
            ZettelWindowManager.shared.createWindow(note: note)
        } else {
            state.loadNote(note)
        }
        state.isShowingPicker = false
    }

    private func deleteNote(_ note: Note) {
        MacNoteStore.shared.deleteNote(note)
    }
}

// MARK: - Note Picker Row

private struct NotePickerRow: View {
    let note: Note
    let onOpen: () -> Void
    let onDelete: () -> Void

    @State private var isHovering = false

    var body: some View {
        HStack(spacing: 0) {
            Button(action: onOpen) {
                VStack(alignment: .leading, spacing: 2) {
                    Text(note.title.isEmpty ? note.autoGeneratedTitle : note.title)
                        .font(.system(size: 13, weight: .medium))
                        .foregroundStyle(.primary)
                        .lineLimit(1)

                    if !note.contentPreview.isEmpty {
                        Text(note.contentPreview)
                            .font(.system(size: 11))
                            .foregroundStyle(.secondary)
                            .lineLimit(1)
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
            }
            .buttonStyle(.plain)

            Spacer(minLength: 8)

            if isHovering {
                Button(action: onDelete) {
                    Image(systemName: "trash")
                        .font(.system(size: 11))
                        .foregroundStyle(.red.opacity(0.85))
                }
                .buttonStyle(.plain)
                .help(String(localized: "mac.picker.delete_note", defaultValue: "Delete Note", comment: "Picker row delete action"))
                .padding(.leading, 8)
            }
        }
        .padding(.horizontal, 10)
        .padding(.vertical, 8)
        .background {
            RoundedRectangle(cornerRadius: 8)
                .fill(isHovering ? Color.accentColor.opacity(0.14) : .clear)
        }
        .contentShape(Rectangle())
        .onHover { hovering in
            isHovering = hovering
        }
    }
}
