//
//  ZettelEditorView.swift
//  ZettelMac
//
//  Main per-window view containing the title field, text editor,
//  toolbar buttons (pin, list, new), and the note picker popover.
//  Toolbar items automatically receive Liquid Glass on macOS 26.
//

import SwiftUI
import ZettelKit

struct ZettelEditorView: View {
    @Bindable var state: ZettelWindowState

    var body: some View {
        editorContent
        .overlay(alignment: .topTrailing) {
            pickerPopoverAnchor
        }
        .frame(minWidth: 320, minHeight: 280)
        .background(.ultraThinMaterial)
        .toolbar {
            ToolbarItem(placement: .principal) {
                EditableWindowTitleView(state: state)
            }

            ToolbarItemGroup(placement: .primaryAction) {
                // List / Picker button
                Button {
                    state.isShowingPicker.toggle()
                } label: {
                    Label("Browse Notes", systemImage: "list.bullet")
                }
                .help("Browse Notes (⌘O)")
                .keyboardShortcut("o", modifiers: .command)

                // Pin button
                Button {
                    ZettelWindowManager.shared.togglePin(id: state.windowId)
                } label: {
                    Label("Pin Window", systemImage: state.isPinned ? "pin.fill" : "pin")
                }
                .help("Pin Window (⌘P)")

                // New note button
                Button {
                    state.clearToNewNote()
                    ZettelWindowManager.shared.updateWindowTitle(id: state.windowId)
                } label: {
                    Label("New Note", systemImage: "plus")
                }
                .help("New Note (⌘N)")
            }
        }
        .onChange(of: state.note.title) { _, _ in
            Task { @MainActor in
                ZettelWindowManager.shared.updateWindowTitle(id: state.windowId)
            }
        }
    }

    private var pickerPopoverAnchor: some View {
        Color.clear
            .frame(width: 1, height: 1)
            .allowsHitTesting(false)
            .popover(
                isPresented: $state.isShowingPicker,
                attachmentAnchor: .point(.topTrailing),
                arrowEdge: .top
            ) {
                NotePicker(state: state)
            }
    }

    // MARK: - Editor Content

    private var editorContent: some View {
        // Note content only — title is shown in the window titlebar
        MacTextEditor(
            text: Binding(
                get: { state.note.content },
                set: { state.updateContent($0) }
            )
        )
        .background {
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .fill(Color(nsColor: .textBackgroundColor))
                .shadow(color: .black.opacity(0.08), radius: 6, y: 2)
        }
        .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
        .padding(10)
    }
}

private struct EditableWindowTitleView: View {
    @Bindable var state: ZettelWindowState

    @State private var isShowingEditor = false
    @State private var draftTitle = ""
    @FocusState private var isEditorFocused: Bool

    private var resolvedTitle: String {
        state.note.title.isEmpty ? state.note.autoGeneratedTitle : state.note.title
    }

    var body: some View {
        Button(action: beginEditing) {
            Text(resolvedTitle)
                .font(.system(size: 13, weight: .semibold))
                .foregroundStyle(.primary)
                .lineLimit(1)
                .truncationMode(.middle)
                .frame(maxWidth: 320)
                .padding(.horizontal, 8)
                .padding(.vertical, 3)
                .clipShape(.rect(cornerRadius: 6))
        }
        .buttonStyle(.plain)
        .popover(
            isPresented: $isShowingEditor,
            attachmentAnchor: .point(.bottom),
            arrowEdge: .top
        ) {
            editorPopover
        }
    }

    private var editorPopover: some View {
        TextField(String(localized: "mac.title_editor.placeholder"), text: $draftTitle)
            .textFieldStyle(.roundedBorder)
            .font(.system(size: 36, weight: .regular, design: .rounded))
            .focused($isEditorFocused)
            .onSubmit(saveAndClose)
            .padding(16)
            .frame(width: 440)
            .background(.regularMaterial)
            .onAppear {
                isEditorFocused = true
            }
            .onDisappear {
                draftTitle = state.note.title
                isEditorFocused = false
            }
            .onKeyPress(.escape) {
                cancelAndClose()
                return .handled
            }
    }

    private func beginEditing() {
        draftTitle = resolvedTitle
        isShowingEditor = true
    }

    private func saveAndClose() {
        state.updateTitle(draftTitle)
        ZettelWindowManager.shared.updateWindowTitle(id: state.windowId)
        isShowingEditor = false
    }

    private func cancelAndClose() {
        draftTitle = state.note.title
        isShowingEditor = false
    }
}
