//
//  Note.swift
//  ZettelKit
//
//  Core note model shared between iOS and macOS targets.
//

import Foundation

/// Errors related to note operations
public enum NoteError: LocalizedError, Sendable {
    case corruptedFile
    case fileSystemError(String)
    case encodingError

    public var errorDescription: String? {
        switch self {
        case .corruptedFile:
            return "The note file is corrupted."
        case .fileSystemError(let message):
            return "File system error: \(message)"
        case .encodingError:
            return "Failed to encode or decode the note."
        }
    }
}

/// Wrapper class for cached tag data to work with NSCache
public final class CachedTags: @unchecked Sendable {
    public let hash: Int
    public let tags: Set<String>

    public init(hash: Int, tags: Set<String>) {
        self.hash = hash
        self.tags = tags
    }
}

/// Thread-safe cache manager for tag extraction to avoid repeated regex operations
public final class TagCacheManager: @unchecked Sendable {
    public static let shared = TagCacheManager()

    private let cache = NSCache<NSString, CachedTags>()
    private let cacheQueue = DispatchQueue(label: "com.Zettel.tagcache", attributes: .concurrent)

    private init() {
        cache.countLimit = CacheConstants.tagCacheLimit
        cache.totalCostLimit = CacheConstants.tagCacheSizeLimit
    }
    
    public func getExtractedTags(for note: Note) -> Set<String> {
        let noteId = note.id
        let contentHash = (note.title + note.content).hashValue

        return cacheQueue.sync {
            let cacheKey = NSString(string: noteId)
            if let cached = cache.object(forKey: cacheKey), cached.hash == contentHash {
                return cached.tags
            }

            let tags = TagParser.extractTags(from: note)
            let cachedTags = CachedTags(hash: contentHash, tags: tags)
            
            cacheQueue.async(flags: .barrier) {
                self.cache.setObject(cachedTags, forKey: NSString(string: noteId))
            }

            return tags
        }
    }

    public func invalidateCache(for noteId: String) {
        cacheQueue.async(flags: .barrier) {
            self.cache.removeObject(forKey: NSString(string: noteId))
        }
    }
    
    public func clearCache() {
        cacheQueue.async(flags: .barrier) {
            self.cache.removeAllObjects()
        }
    }
}

/// Represents a note in the Zettel application.
///
/// Each note is identified by its filename, making the system simple and straightforward.
public struct Note: Identifiable, Codable, Equatable, Sendable {
    /// Display title of the note
    public var title: String
    
    /// Full markdown content of the note
    public var content: String
    
    /// Timestamp when the note was created
    public var createdAt: Date
    
    /// Timestamp when the note was last modified
    public var modifiedAt: Date
    
    /// Indicates if this note is a cloud stub (not yet downloaded)
    public var isCloudStub: Bool = false
    
    /// Indicates if this cloud stub is currently being downloaded
    public var isDownloading: Bool = false
    
    /// URL to the cloud file (only set for cloud stubs)
    public var cloudURL: URL?

    /// String identifier derived from filename for Identifiable conformance
    public var id: String {
        return filename
    }
    
    // MARK: - Codable Support
    
    enum CodingKeys: String, CodingKey {
        case title
        case content
        case createdAt
        case modifiedAt
    }
    
    public init(title: String = "", content: String = "") {
        self.title = title
        self.content = content
        let now = Date()
        self.createdAt = now
        self.modifiedAt = now
    }
    
    /// Updates the content and modifies the timestamp
    public mutating func updateContent(_ newContent: String) {
        self.content = newContent
        self.modifiedAt = Date()
        TagCacheManager.shared.invalidateCache(for: self.filename)
    }

    /// Updates the title and modifies the timestamp
    public mutating func updateTitle(_ newTitle: String) {
        let oldFilename = self.filename
        self.title = newTitle
        self.modifiedAt = Date()
        TagCacheManager.shared.invalidateCache(for: oldFilename)
        TagCacheManager.shared.invalidateCache(for: self.filename)
    }
    
    /// Returns the auto-generated title based on creation date (filesystem-safe)
    public var autoGeneratedTitle: String {
        return DefaultTitleTemplateManager.shared.generateTitle(for: createdAt)
    }
    
    /// Returns the filename for saving this note
    public var filename: String {
        let cleanTitle = sanitizeForFilename(title.isEmpty ? autoGeneratedTitle : title)
        return "\(cleanTitle).md"
    }

    /// Generates a unique filename by checking for collisions and adding counters
    public func generateUniqueFilename(in directory: URL) -> String {
        let baseTitle = sanitizeForFilename(title.isEmpty ? autoGeneratedTitle : title)
        var filename = "\(baseTitle).md"
        var counter = 1

        while FileManager.default.fileExists(atPath: directory.appendingPathComponent(filename).path) {
            filename = "\(baseTitle)_\(counter).md"
            counter += 1
        }

        return filename
    }
    
    /// Sanitizes a string for use as a filename by replacing illegal characters
    private func sanitizeForFilename(_ input: String) -> String {
        var sanitized = input.replacingOccurrences(of: ":", with: "-")
        let illegalCharacters = CharacterSet(charactersIn: "/\\*?\"<>|")
        sanitized = sanitized
            .components(separatedBy: illegalCharacters)
            .joined()
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return sanitized.isEmpty ? "Untitled" : sanitized
    }
    
    /// Returns a preview of the content (first few lines for overview)
    public var contentPreview: String {
        return contentPreview(maxLines: 3)
    }
    
    /// Returns a preview of the content with specified max lines
    public func contentPreview(maxLines: Int) -> String {
        let lines = content.components(separatedBy: .newlines)
        let previewLines = lines.prefix(maxLines)
        let preview = previewLines.joined(separator: "\n")
        return preview.isEmpty ? "" : preview
    }
    
    /// Serializes the note as plain markdown content
    public var serializedContent: String {
        return content
    }

    /// Creates a Note from content with optional metadata
    public static func fromSerializedContent(_ content: String, fallbackTitle: String? = nil) -> Note {
        return Note(title: fallbackTitle ?? "", content: content)
    }
    
    /// Creates a Note from content with file metadata timestamps
    public static func fromSerializedContent(_ content: String, fallbackTitle: String? = nil, createdAt: Date, modifiedAt: Date) -> Note {
        var note = Note(title: fallbackTitle ?? "", content: content)
        note.createdAt = createdAt
        note.modifiedAt = modifiedAt
        return note
    }
    
    // MARK: - Tag Support
    
    /// Extracts all tags from both title and content
    public var extractedTags: Set<String> {
        return TagCacheManager.shared.getExtractedTags(for: self)
    }
    
    /// Returns all tags as Tag objects (for display purposes)
    public var tagObjects: [Tag] {
        return extractedTags.map { Tag(name: $0) }.sorted { $0.displayName < $1.displayName }
    }
    
    /// Checks if the note contains a specific tag (case-insensitive)
    public func hasTag(_ tagName: String) -> Bool {
        return extractedTags.contains(tagName.lowercased())
    }
    
    /// Returns a formatted string of all tags for display
    public var tagDisplayString: String {
        let sortedTags = extractedTags.sorted()
        return sortedTags.map { "#\($0)" }.joined(separator: " ")
    }
}

// MARK: - Input Validation

extension Note {
    /// Validates note content and returns validation errors
    public func validate() -> [NoteValidationError] {
        var errors: [NoteValidationError] = []
        
        if title.count > ValidationConstants.maxNoteTitleLength {
            errors.append(.titleTooLong(title.count, ValidationConstants.maxNoteTitleLength))
        }
        
        if content.count > ValidationConstants.maxNoteContentLength {
            errors.append(.contentTooLong(content.count, ValidationConstants.maxNoteContentLength))
        }
        
        let extractedTags = self.extractedTags
        if extractedTags.count > ValidationConstants.maxTagsPerNote {
            errors.append(.tooManyTags(extractedTags.count, ValidationConstants.maxTagsPerNote))
        }
        
        for tag in extractedTags {
            if tag.count > ValidationConstants.maxTagLength {
                errors.append(.tagTooLong(tag, ValidationConstants.maxTagLength))
            }
        }
        
        return errors
    }
    
    /// Checks if the note is valid
    public var isValid: Bool {
        return validate().isEmpty
    }
    
    /// Sanitizes note content to ensure it's valid
    public mutating func sanitize() {
        title = String(title.prefix(ValidationConstants.maxNoteTitleLength))
        content = String(content.prefix(ValidationConstants.maxNoteContentLength))
        modifiedAt = Date()
    }
}

/// Validation errors for notes
public enum NoteValidationError: LocalizedError, Sendable {
    case titleTooLong(Int, Int)
    case contentTooLong(Int, Int)
    case tooManyTags(Int, Int)
    case tagTooLong(String, Int)
    
    public var errorDescription: String? {
        switch self {
        case .titleTooLong(let current, let max):
            return "Title too long (\(current)/\(max) characters)"
        case .contentTooLong(let current, let max):
            return "Content too long (\(current)/\(max) characters)"
        case .tooManyTags(let current, let max):
            return "Too many tags (\(current)/\(max))"
        case .tagTooLong(let tag, let max):
            return "Tag '\(tag)' too long (max \(max) characters)"
        }
    }
}
