import Foundation
import Testing
@testable import ZettelKit

struct NoteAndTagTests {
    @Test
    func filenameSanitizationUsesFilesystemSafeTitle() {
        let note = Note(title: "  Daily:/\\*?\"<>|  ", content: "Body")
        #expect(note.filename == "Daily-.md")
    }

    @Test
    func whitespaceOnlyTitleFallsBackToUntitled() {
        let note = Note(title: "   ", content: "")
        #expect(note.filename == "Untitled.md")
    }

    @Test
    func autoGeneratedTitleUsesConfiguredTemplateWhenTitleIsEmpty() {
        let defaults = makeIsolatedDefaults()
        let manager = DefaultTitleTemplateManager(userDefaults: defaults, storageKey: "autoTitle")
        manager.saveTemplate("{{shortDate}}")

        var note = Note(title: "", content: "")
        note.createdAt = makeDate(year: 2025, month: 10, day: 19, hour: 8, minute: 0, second: 0)

        #expect(manager.generateTitle(for: note.createdAt) == "2025-10-19")
    }

    @Test
    func uniqueFilenameAddsCounterForCollisions() throws {
        let tempDirectory = try TemporaryDirectory()
        defer { tempDirectory.cleanup() }

        let originalURL = tempDirectory.url.appendingPathComponent("Collision.md")
        try "Existing".write(to: originalURL, atomically: true, encoding: .utf8)

        let note = Note(title: "Collision", content: "New")
        #expect(note.generateUniqueFilename(in: tempDirectory.url) == "Collision_1.md")
    }

    @Test
    func contentPreviewRespectsLineLimit() {
        let note = Note(title: "Preview", content: "One\nTwo\nThree\nFour")
        #expect(note.contentPreview(maxLines: 2) == "One\nTwo")
        #expect(note.contentPreview == "One\nTwo\nThree")
    }

    @Test
    func deserializationPreservesFallbackTitleAndTimestamps() {
        let createdAt = makeDate(year: 2024, month: 12, day: 1, hour: 9, minute: 0, second: 0)
        let modifiedAt = makeDate(year: 2024, month: 12, day: 2, hour: 10, minute: 0, second: 0)

        let note = Note.fromSerializedContent(
            "#tagged content",
            fallbackTitle: "Imported",
            createdAt: createdAt,
            modifiedAt: modifiedAt
        )

        #expect(note.title == "Imported")
        #expect(note.createdAt == createdAt)
        #expect(note.modifiedAt == modifiedAt)
    }

    @Test
    func validationAndSanitizationCatchOversizedContent() {
        let overlongTitle = String(repeating: "T", count: ValidationConstants.maxNoteTitleLength + 5)
        let overlongContent = String(repeating: "C", count: ValidationConstants.maxNoteContentLength + 10)
        var note = Note(title: overlongTitle, content: overlongContent)

        let errors = note.validate()
        #expect(errors.contains { if case .titleTooLong = $0 { true } else { false } })
        #expect(errors.contains { if case .contentTooLong = $0 { true } else { false } })

        note.sanitize()
        #expect(note.title.count == ValidationConstants.maxNoteTitleLength)
        #expect(note.content.count == ValidationConstants.maxNoteContentLength)
    }

    @Test
    func tagParsingNormalizesAndDeduplicatesAcrossTitleAndBody() {
        let note = Note(title: "#Swift", content: "Working on #swift and #Testing")
        #expect(note.extractedTags == ["swift", "testing"])
    }

    @Test
    func hashtagFactoryAcceptsValidNamesAndRejectsInvalidCharacters() {
        #expect(Tag.fromHashtag("#valid_tag")?.id == "valid_tag")
        #expect(Tag.fromHashtag("#Swift")?.displayName == "Swift")
        #expect(Tag.fromHashtag("#not-valid") == nil)
    }

    @Test
    func findHashtagAtPositionHandlesValidAndInvalidInput() {
        let text = "hello #sw"
        let validResult = TagParser.findHashtagAtPosition(text, position: text.count)
        #expect(validResult?.partial == "sw")
        #expect(validResult?.range.location == 6)

        #expect(TagParser.findHashtagAtPosition("hello #sw if", position: 12) == nil)
        #expect(TagParser.findHashtagAtPosition("hello #sw!", position: 10) == nil)
        #expect(TagParser.findHashtagAtPosition("hello", position: 20) == nil)
    }

    @Test
    func replaceHashtagOnlyReplacesSelectedRange() {
        let text = "Work on #sw today"
        let range = NSRange(location: 8, length: 3)
        #expect(TagParser.replaceHashtag(in: text, range: range, with: "swift") == "Work on #swift today")
    }
}
